# Generated by Django 2.2.14 on 2020-08-09 23:44

import autoslug.fields
import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
            options={
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('page_css', models.TextField(blank=True, null=True)),
                ('header_img', models.ImageField(upload_to=blog.models.blog_uploads)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('post', models.TextField()),
                ('page_js', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(to='blog.BlogCategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
