# Generated by Django 2.2.14 on 2020-08-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200810_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='page_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='page_js',
            field=models.TextField(blank=True, null=True),
        ),
    ]
